### ISSUE TITLE
Strange blurry text

### ISSUE THREAD

**Issue by vstepaniuk** [JustOff/moon-pdf-viewer#1]
Link to PDF file (or attach file here): [http://www.stroustrup.com/new_learning.pdf](http://www.stroustrup.com/new_learning.pdf)

Configuration:
- Web browser and its version: Pale Moon Version: 27.3.0 (32-bit)
- Operating system and its version: Windows 7 Ultimate SP1 32-bit
- PDF.js version:
- Is an extension: Moon PDF Viewer 1.0.2

Steps to reproduce the problem:
1. Open the above mentioned link

What is the expected behavior? (add screenshot)
Normal text rendering, as for example seen in these extensions:

Adobe Acrobat 17.9.20044.25828
![acrobat](https://cloud.githubusercontent.com/assets/24701640/26063281/429a96e2-3996-11e7-92d6-30ecd3225f28.png)

Foxit Reader Plugin for Mozilla 2.2.6.1206
![foxit](https://cloud.githubusercontent.com/assets/24701640/26063266/32563f48-3996-11e7-911a-5757ace8712a.png)

SumatraPDF Browser Plugin 2.5.2.0
![sumatrapdf_3](https://cloud.githubusercontent.com/assets/24701640/26063292/4a2381f8-3996-11e7-9083-9e08758163ac.png)

What went wrong? (add screenshot)
Some zones of text look blurry:
![moon_pdf_viewer](https://cloud.githubusercontent.com/assets/24701640/26063410/a8fc14ba-3996-11e7-8087-b3296acaf134.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[https://addons.palemoon.org/addon/moon-pdf-viewer/](https://addons.palemoon.org/addon/moon-pdf-viewer/)

**Comment by JustOff** [comment]
Unfortunately I can't reproduce this problem, the page you mentioned looks differently for me and not blurry at all. Actually Moon PDF Viewer (PDF.js) uses browser rendering engine to display PDF content, so it can nothing to do if some fonts looks blurry at some zoom levels. You can try to play with browser settings (DirectX mode, etc), OS graphics card drivers, change zoom level or just use external PDF viewer if it suits better for you.

**Comment by vstepaniuk** [comment]
Could you upload your screenshots? Thanks.

**Comment by JustOff** [comment]
![palemoon_2017-05-15_19-56-48](https://cloud.githubusercontent.com/assets/340855/26069238/daae7810-39a8-11e7-816c-4e8c2c097148.png)

**Comment by vstepaniuk** [comment]
Don't hurry to close the issue...
Could you please enable ClearType in Windows and send a new screenshot? Thank you!

**Comment by JustOff** [comment]
I will not do it just for testing 'cause I hate ClearType and once enabled it takes too many steps to turn it off completely. Anyway as I already wrote I can't control font rendering from add-on in any way.
